"""Vault git backup: attributed commits into a git dir kept outside the vault.

The vault directory typically lives inside a synced folder (iCloud Drive),
where a ``.git`` directory would be corrupted by the sync engine — so the
repository lives elsewhere (``state_dir/vault.git`` by default) and every git
call names both locations explicitly (``--git-dir`` + ``--work-tree``). The
vault itself carries no git marker at all.

Two commit paths:

- ``commit_run`` — called after an agent run that mutated the vault. It stages
  only the paths that run touched, so concurrent conversations cannot leak
  each other's in-flight writes into the wrong commit, and the message carries
  the triggering interaction (user message + bot reply) for `git log` debugging.
- ``sweep`` — a slow periodic pass (plus one at startup via ``init_repo``)
  that commits whatever no run claimed: edits arriving from other devices via
  the sync engine, or writes orphaned by a crash before their commit ran.

``lock`` serializes commits with vault mutations: the agent holds it around
mutating tool calls, so a commit never snapshots a file mid-write. Sweeps
refuse to run while iCloud eviction placeholders (``*.icloud``) are present —
an evicted file must not be committed as a deletion.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import Iterable
from pathlib import Path

logger = logging.getLogger(__name__)

_SWEEP_INTERVAL = 300.0
_SLUG_MAX = 72
_BODY_MAX = 2000
_GIT_OUTPUT_MAX = 500
# Derived views regenerated by background tasks: committing them would bury
# the real history in noise, and they rebuild from state_dir anyway.
_EXCLUDED = ("system/usage.md",)
_ICLOUD_SUFFIX = ".icloud"


def _build_message(trigger: str, response: str) -> str:
    """Commit message: first trigger line as subject, full interaction as body."""
    trigger = trigger.strip()
    response = response.strip()
    subject = trigger.splitlines()[0] if trigger else "(no trigger)"
    if len(subject) > _SLUG_MAX:
        subject = subject[: _SLUG_MAX - 1] + "…"
    return (
        f"{subject}\n\n"
        f"trigger: {trigger[:_BODY_MAX]}\n\n"
        f"response: {response[:_BODY_MAX]}\n"
    )


class VaultBackup:
    """Local-only git history of the vault; never pushes anywhere."""

    def __init__(self, vault_path: Path, git_dir: Path) -> None:
        self._vault = vault_path
        self._git_dir = git_dir
        self._lock = asyncio.Lock()
        self._pending: set[asyncio.Task[None]] = set()

    @property
    def lock(self) -> asyncio.Lock:
        """Held around vault mutations and commits so neither sees the other mid-flight."""
        return self._lock

    async def _run_git(self, *args: str) -> tuple[int, str]:
        proc = await asyncio.create_subprocess_exec(
            "git",
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            cwd=self._vault,
        )
        out, _ = await proc.communicate()
        return proc.returncode or 0, out.decode(errors="replace")

    async def _git(self, *args: str) -> tuple[int, str]:
        return await self._run_git(
            "--git-dir", str(self._git_dir), "--work-tree", str(self._vault), *args
        )

    async def init_repo(self) -> None:
        """Create the repo if missing, pin its config, and sweep a baseline."""
        if not (self._git_dir / "HEAD").exists():
            self._git_dir.parent.mkdir(parents=True, exist_ok=True)
            code, out = await self._run_git(
                "init", "--bare", "--initial-branch=main", str(self._git_dir)
            )
            if code != 0:
                logger.error("vault backup: git init failed: %s", out.strip())
                return
        # Repo-local identity and no signing/hooks: background commits must
        # not depend on (or be broken by) whatever global config the host has.
        await self._git("config", "user.name", "noxide")
        await self._git("config", "user.email", "noxide@localhost")
        await self._git("config", "commit.gpgsign", "false")
        # --bare left core.bare=true, which git rejects in combination with
        # core.worktree — and persisting core.worktree is the documented way
        # for the user to inspect history without --work-tree on every call.
        # The bot itself is unaffected either way: it always passes the flag.
        await self._git("config", "core.bare", "false")
        exclude = self._git_dir / "info" / "exclude"
        exclude.parent.mkdir(exist_ok=True)
        exclude.write_text("".join(f"/{path}\n" for path in _EXCLUDED), encoding="utf-8")
        await self.sweep(reason="startup")

    async def commit_run(self, paths: Iterable[str], trigger: str, response: str) -> None:
        """Commit exactly *paths* with the interaction that produced them."""
        pathspecs = sorted(p for p in paths if p)
        if not pathspecs:
            return
        try:
            async with self._lock:
                code, out = await self._git("add", "-A", "--", *pathspecs)
                if code != 0:
                    # One bad pathspec fails the whole call; salvage the rest.
                    logger.warning("vault backup: git add failed: %s", out.strip()[:_GIT_OUTPUT_MAX])
                    for path in pathspecs:
                        await self._git("add", "-A", "--", path)
                await self._commit(_build_message(trigger, response))
        except Exception:
            logger.exception("vault backup: commit failed")

    def schedule_commit(self, paths: Iterable[str], trigger: str, response: str) -> None:
        """Fire-and-forget ``commit_run`` so replies are never delayed by git."""
        task = asyncio.create_task(self.commit_run(set(paths), trigger, response))
        self._pending.add(task)
        task.add_done_callback(self._pending.discard)

    async def sweep(self, reason: str = "unattributed changes") -> None:
        """Commit everything dirty that no run claimed (external edits, crash leftovers)."""
        async with self._lock:
            code, out = await self._git("status", "--porcelain")
            if code != 0:
                logger.warning("vault backup: git status failed: %s", out.strip()[:_GIT_OUTPUT_MAX])
                return
            if not out.strip():
                return
            if any(line.rstrip().endswith(_ICLOUD_SUFFIX) for line in out.splitlines()):
                logger.warning(
                    "vault backup: iCloud eviction placeholders in the vault; "
                    "skipping sweep so evicted files are not committed as deletions"
                )
                return
            code, out = await self._git("add", "-A")
            if code != 0:
                logger.warning("vault backup: git add failed: %s", out.strip()[:_GIT_OUTPUT_MAX])
                return
            await self._commit(f"vault sweep: {reason}")

    async def _commit(self, message: str) -> None:
        code, out = await self._git("commit", "--no-verify", "-m", message)
        if code != 0 and "nothing to commit" not in out and "nothing added to commit" not in out:
            logger.warning("vault backup: git commit failed: %s", out.strip()[:_GIT_OUTPUT_MAX])

    async def run(self) -> None:
        """Periodic sweep loop; cancelled at shutdown."""
        while True:
            await asyncio.sleep(_SWEEP_INTERVAL)
            try:
                await self.sweep()
            except Exception:
                logger.exception("vault backup: sweep failed")

    async def drain(self) -> None:
        """Wait for background commits already scheduled; used at shutdown."""
        # Snapshot: the done-callbacks that empty _pending run via call_soon,
        # so looping until the set empties could spin without ever yielding.
        if self._pending:
            await asyncio.gather(*tuple(self._pending), return_exceptions=True)
